# Generated by Django 2.0.2 on 2018-03-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=264)),
            ],
            options={
                'verbose_name_plural': 'Companies database',
            },
        ),
        migrations.CreateModel(
            name='People_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite_food', models.CharField(max_length=264)),
            ],
            options={
                'verbose_name_plural': 'People database',
            },
        ),
    ]
