# Generated by Django 2.0.2 on 2018-03-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paranuara', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies_db',
            name='company_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='people_db',
            name='favourite_food',
            field=models.TextField(),
        ),
    ]
