# Generated by Django 2.0.2 on 2018-03-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paranuara', '0003_remove_people_db_favourite_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies_db',
            name='index',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people_db',
            name='_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people_db',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people_db',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people_db',
            name='age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people_db',
            name='balance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people_db',
            name='company_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people_db',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people_db',
            name='eye_color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people_db',
            name='favourite_food',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people_db',
            name='friends',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people_db',
            name='gender',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people_db',
            name='greeting',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people_db',
            name='guid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people_db',
            name='has_died',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people_db',
            name='index',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people_db',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people_db',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people_db',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people_db',
            name='registered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people_db',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companies_db',
            name='company_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
